=== stakah/Mobile1/src/main/resources/static/raml/aol/schemas/alunoAviso-schema.json
{
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "required" : true ,
  "properties" : {
    "Aluno" : {
      "required" : false ,
      "type" : "object" ,
      "properties" : {
        "Id" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Matricula" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Nome" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Periodo" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Sala" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Turma" : {
          "required" : false ,
          "type" : "string"
        } ,
        "User" : {
          "required" : false ,
          "type" : "string"
        }
      }
    } ,
    "Aviso" : {
      "required" : false ,
      "type" : "object" ,
      "properties" : {
        "Content" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Id" : {
          "required" : false ,
          "type" : "string"
        } ,
        "Title" : {
          "required" : false ,
          "type" : "string"
        }
      }
    } ,
    "Enviado" : {
      "required" : false ,
      "type" : "boolean"
    } ,
    "Lido" : {
      "required" : false ,
      "type" : "boolean"
    } ,
    "Id" : {
      "required" : false ,
      "type" : "string"
    }
  }
}

=== stakah/Mobile1/src/main/mobileapp/static/raml/aol/examples/alunoAviso-example.json
{
  "Aluno" : {
    "Id" : "str1234" ,
    "Matricula" : "str1234" ,
    "Nome" : "str1234" ,
    "Periodo" : "str1234" ,
    "Sala" : "str1234" ,
    "Turma" : "str1234" ,
    "User" : "str1234"
  } ,
  "Aviso" : {
    "Content" : "str1234" ,
    "Id" : "str1234" ,
    "Title" : "str1234"
  } ,
  "Enviado" : true ,
  "Lido" : true ,
  "Id" : "str1234"
}
